### ISSUE TITLE
Working Sample code for data ingest

### ISSUE THREAD

**Issue by arcadius** [Enterprise-Content-Management/infoarchive-sip-sdk#14]
Hello @RemonSinnema 

Any chance we could get some woking samples in showing how to use the Java API for data ingestion?

Seems you are currently working on this at 
https://github.com/Enterprise-Content-Management/infoarchive-sip-sdk/tree/master/samples
?

Thanks.

**Comment by RaySinnema** [comment]
It's on the roadmap, but it'll be a while.

**Comment by arcadius** [comment]
@RemonSinnema 

Trying to understand the format of an authenticated rest API call ...

```
$ curl --header "Accept: application/hal+json;UTF-8" --header "Authorization: Basic YWRhbUBpYWN1c3R
vbWVyLmNvbTpw-YXNzd29yZA==" http://localhost:8765/services
{
  "name" : "InfoArchive Home Resource",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8765/services"
    },
    "http://identifiers.emc.com/product-info" : {
      "href" : "http://localhost:8765/product-info"
    }
  }
}
```

Is that the correct header format?
Still, I cannot see the tenant in the response.

Many thanks

**Comment by RaySinnema** [comment]
@arcadius , this is not an InfoArchive support forum. Please consult your documentation.
