### ISSUE TITLE
Ingest SIPs through SIP SDK 

### ISSUE THREAD

**Issue by Manoranjan1987** [Enterprise-Content-Management/infoarchive-sip-sdk#17]
We have contributed a sample code for SIP Ingest through SIP SDK. However, the sample is having issues right now which could either be due to some missing configuration or due to SIP SDK. Please can you reva the pull request#16 containing the sample code and suggest the required changes.

**Comment by RaySinnema** [comment]
I've added `samples/sample-3-ingest`.

**Comment by Manoranjan1987** [comment]
@RemonSinnema 

Thank you for the sample ingest code, really appreciate your support. We are trying to work with this now.

Can we request you to include all configurations like search, query etc as we used in our sample code (pushed to gitHub earlier) for Application creation before Ingesting SIPs. Our scope of work includes application creation followed by ingest.
