### ISSUE TITLE
Application Description and Category Missing - InfoArchive Homepage 

### ISSUE THREAD

**Issue by AswiniChandrasekaran3** [Enterprise-Content-Management/infoarchive-sip-sdk#18]
Hi @RemonSinnema,
Any Application created using SIP SDK is missing "Description" and "Category" in Homepage as shown in the attached screenshot. 
![applicationhome](https://cloud.githubusercontent.com/assets/27808725/25225448/4de24dc4-25b9-11e7-9d97-243bc030b4b2.PNG)

See https://github.com/Enterprise-Content-Management/infoarchive-sip-sdk/blob/master/core/src/main/java/com/emc/ia/sdk/sip/client/dto/Application.java#L9

Thanks,
Aswini

**Comment by RaySinnema** [comment]
Thanks for reporting this. It's fixed in 5.5.10, which should be available from Maven Central in a little while.

**Comment by AswiniChandrasekaran3** [comment]
@RemonSinnema 
Thank you Remon
