### ISSUE TITLE
Expand ingestion sample with content and search

### ISSUE THREAD

**Issue by AswiniChandrasekaran3** [Enterprise-Content-Management/infoarchive-sip-sdk#19]
Hi @RemonSinnema ,
Thank you for the ingest sample code - samples/sample3. 

Looking at the sample, I see that the SIP is having only eas_sip.xml and eas_pdi.xml and missing the actual content file. I am sure you would agree that, in a typical ECM platform we will have SIPs with actual content files and associated search configuration.

Hence, I modified samples/sample3 attempting to ingest a SIP with some content. In order to achieve this, I made changes in pdi.xml, pdi-schema.xsd and created a new SIP. 

While I have been able to ingest a SIP with content, I have not been able to search & retrieve the ingested SIP via IA UI(Basically, I do not get any search results, please see attached). 

Would you be kind enough to update the samples/sample3 code to include  the below

1. Ingest a SIP with some content
2. Enable search & retrieve of the ingested SIP content through IA UI.

Just adding the pdi-schema.xsd for your reference.
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="urn:emc:ia:schema:sample:animal:1.0" xmlns:ns1="urn:emc:ia:schema:sample:animal:1.0">
    <xs:element name="animals">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ns1:animal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="animal">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ns1:AnimalName"/>
                <xs:element ref="ns1:FileName"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="AnimalName" type="xs:string"/>
    <xs:element name="FileName" type="xs:string"/>
</xs:schema>

```
Thank You very much @RemonSinnema .
Aswini

![snipimage](https://cloud.githubusercontent.com/assets/27808725/25247601/35538e86-2603-11e7-832c-d0ec1423daf8.JPG)

**Comment by RaySinnema** [comment]
@kovaloid is working on this.
