### ISSUE TITLE
Support other stores than local File Store (e.g. ECS / S3 / CAS)

### ISSUE THREAD

**Issue by AswiniChandrasekaran3** [Enterprise-Content-Management/infoarchive-sip-sdk#20]
Hi @RemonSinnema ,
I see that currently the SIP SDK configuration is creating only local Folder Store which is "filestore_01" as mentioned in the link below

https://github.com/Enterprise-Content-Management/infoarchive-sip-sdk/blob/master/core/src/main/java/com/emc/ia/sdk/configurer/PropertyBasedConfigurer.java#L50

Since options to choose filestore from - ECS / S3 / CAS are available OOTB., can you include the required configurations for each of these please ?
![image](https://cloud.githubusercontent.com/assets/27808725/25383010/efa6e4fc-29b1-11e7-80c0-095ea365da5c.png)

Thank You.

**Comment by RaySinnema** [comment]
We welcome contributions ;)
