### ISSUE TITLE
Support SIP encryption

### ISSUE THREAD

**Issue by Manoranjan1987** [Enterprise-Content-Management/infoarchive-sip-sdk#21]
Hi @RemonSinnema ,

Hope you are doing well, thank you for your continued efforts on this forum.

We are using SIP SDK to ingest SIPs with content, we will be contributing the working code very shortly.

We would want to perform SIP encryption (Bouncy Castle encryption) on the ingested SIPs in IA. Would you  be able to update SIP SDK to include encryption ?

Thank You very much.

**Comment by kovaloid** [comment]
Now in order to work with encryption in SIP-SDK you should add some extra parameters to existing configuration.
1) Creating crypto object:
```
ia.crypto.object.name = MyCryptoObject
ia.crypto.object.security.provider = Bouncy Castle
ia.crypto.object.key.size = 256
ia.crypto.object.in.use = true
ia.crypto.object.encryption.mode = CBC
ia.crypto.object.padding.scheme = PKCS7PADDING
ia.crypto.object.encryption.algorithm = AES
```
2) Creating pdi crypto:
```
ia.pdi.crypto.name = MyPdiCrypto
```
3) Creating holding crypto:
```
ia.holding.crypto.name = MyHoldingCrypto
ia.holding.crypto.encoding = base64
ia.holding.crypto.enabled = true
```

**Comment by RaySinnema** [comment]
I've started a [wiki page](https://github.com/Enterprise-Content-Management/infoarchive-sip-sdk/wiki/Configuring-encryption) to explain this. Could you please elaborate on it to explain to SIP SDK users when they should do what?

**Comment by kovaloid** [comment]
@RemonSinnema Okay, sure.
