### ISSUE TITLE
Request for thread-safety

### ISSUE THREAD

**Issue by tftilma** [Enterprise-Content-Management/infoarchive-sip-sdk#34]
So, our client uses a huge amount of files, which need to be archived. It takes a few weeks (!!) just to create the sips. So the idea is to use parallelism. You can use several nodes (computers/servers), several (independent) processes or several threads. 
Several nodes is not an option for us. We do use 2 processes, but we need the memory so more then 2 is not feasible. We also run into configuration, handling, and monitoring nightmare. 
So that only leaves multi-threaded as an option, however, in order to make this work, all our code and all InfoArchive code must be thread-save.  The request is to make this SDK thread save. If one thread uses data, and makes decisions but another changes that same data then its not difficult to understand total chaos will arise. As administrator you will see corrupt sip/zip files which cannot be opened by windows (they can be opened with 7-sip, and they reveal missing mandatory eas_pdi.xml and eas_sip.xml files). So InfoArchive (not the SDK) cannot "ant receive-ingest" them.

What would be needed is splitting the code into Singletons (there's only one instance) and Pojos (there are many, but can easily be reused, and each thread uses their own).

Example issues are: 
BatchSipAssembler.current 
DataSubmissionSession.DataSubmissionSessionBuilder and all those fields
PackagingInformation.PackagingInformationBuilder and all those fields
SipAssembler.pdibuffer, sipFileBuffer, pdiHash, metrics
and many more!

**Comment by RaySinnema** [comment]
Please check the 6.1.0 version that was released today; it contains PR https://github.com/Enterprise-Content-Management/infoarchive-sip-sdk/pull/33 that Atos proposed earlier to address the same issue. Do you still run into issues with these fixes in place?

**Comment by RaySinnema** [comment]
Please check the 6.2.0 version.

**Comment by RaySinnema** [comment]
Closed for lack of feedback.
