### ISSUE TITLE
Program hangs

### ISSUE THREAD

**Issue by Sornix** [Enterprise-Content-Management/infoarchive-sip-sdk#40]
Hi,

  For JWT refresh needs, there is a thread managed in DefaultClock class which hangs execution.
  Probably it would be great to add a close() function in ArchiveClient to cancel active timer. 

Regards,
Olivier

**Comment by RaySinnema** [comment]
Thanks for reporting this, Olivier.

Do you mean that the application is done, but fails to close because there is a non-daemon thread running to refresh the JWT token?

**Comment by Sornix** [comment]
Hi, you are right, the fact to declare thread as daemon will resolve this issue.

**Comment by RaySinnema** [comment]
This issue should be fixed in version 9.10.1.
