### ISSUE TITLE
ArchiveClients doesn't work correctly with many Aplications

### ISSUE THREAD

**Issue by batyanch** [Enterprise-Content-Management/infoarchive-sip-sdk#43]
We have experienced an error  "Application " + applicationName + " not found." with ArchiveClients getApplication method when there are many Applications and rest response is paged. This method iterate only first page:
 InfoArchiveLinkRelations.LINK_APPLICATIONS is _http://localhost:8765/systemdata/tenants/7be2689a-0d3-4e89-9bc7-0de0d0c82389/applications_ but restClient.folow method work with http://localhost:8765/systemdata/tenants/7be2689a-0d83-4e89-9bc7-0de0d0c82389/applications?page=0&size=10

`private static Application getApplication(RestClient restClient, Tenant tenant, String applicationName)
      throws IOException {
    Applications applications = restClient.follow(tenant, InfoArchiveLinkRelations.LINK_APPLICATIONS,
        Applications.class);
    return Objects.requireNonNull(applications.byName(applicationName),
        "Application " + applicationName + " not found.");
  }`

**Comment by sgijsenot** [comment]
Version 11.2.3 no longer uses paging when finding the application.
Please verify whether this fully resolves the issue for you. Thanks.

**Comment by batyanch** [comment]
We have this error. I'm very sorry. My English seems are not so good and I mislead you. Link (http://localhost:8765/systemdata/tenants/7be2689a-0d3-4e89-9bc7-0de0d0c82389/applications) is fine. There is no need to remove page query parameters because there are not any. 
Paged response is from server side. 
Your followNonPaged method should get all links and iterate `next` links that paginated collection provided. 
Sorry for inconvenience.

**Comment by sgijsenot** [comment]
Without paging parameters (page and size), the server should not limit the number of results, so paging would then be unnecessary. I will review this again.

**Comment by batyanch** [comment]
Yes. You are right. But seems REST server is configure with default page and size.
GET on http://192.168.213.178:8765/systemdata/tenants/7be2689a-0d83-4e89-9bc7-0de0d0c82389/applications returns this:
    "_links": {
        "first": {
            "href": "http://192.168.213.178:8765/systemdata/tenants/7be2689a-0d83-4e89-9bc7-0de0d0c82389/applications?limit=20&page=0&size=10"
        },
        "self": {
            "href": "http://192.168.213.178:8765/systemdata/tenants/7be2689a-0d83-4e89-9bc7-0de0d0c82389/applications?limit=20&page=0&size=10"
        },
        "next": {
            "href": "http://192.168.213.178:8765/systemdata/tenants/7be2689a-0d83-4e89-9bc7-0de0d0c82389/applications?limit=20&page=1&size=10"
        },
        "last": {
            "href": "http://192.168.213.178:8765/systemdata/tenants/7be2689a-0d83-4e89-9bc7-0de0d0c82389/applications?limit=20&page=1&size=10"
        },
        "http://identifiers.emc.com/add": {
            "href": "http://192.168.213.178:8765/systemdata/tenants/7be2689a-0d83-4e89-9bc7-0de0d0c82389/applications"
        }
    },
    "page": {
        "size": 10,
        "totalElements": 11,
        "totalPages": 2,
        "number": 0
    }

**Comment by sgijsenot** [comment]
I have just concluded the same. I was too quick with my previous comment, as there is a default at the server side, but that is first overridden by a different setting. I will replace this in followNonPaged with a specific page, size and limit. That should resolve this issue without needing multiple requests to the server.

**Comment by batyanch** [comment]
Yeah. This workaround will be fine. Big enough size parameter do work well.
    "_links": {
        "self": {
            "href": "http://192.168.213.178:8765/systemdata/tenants/7be2689a-0d83-4e89-9bc7-0de0d0c82389/applications?page=0&size=1000"
        },
        "http://identifiers.emc.com/add": {
            "href": "http://192.168.213.178:8765/systemdata/tenants/7be2689a-0d83-4e89-9bc7-0de0d0c82389/applications"
        }
    },
    "page": {
        "size": 1000,
        "totalElements": 11,
        "totalPages": 1,
        "number": 0
    }

**Comment by sgijsenot** [comment]
This functionality has been included in release 11.2.4.

**Comment by batyanch** [comment]
I have tested 11.2.4.
No errors. 
Thanks
