### ISSUE TITLE
Memeory leak for large set of data

### ISSUE THREAD

**Issue by AmuthanGit** [Enterprise-Content-Management/infoarchive-sip-sdk#48]
Hello All,
I am using SIP SDK jar to create SIPs. Getting the rows from the database table then creating sips accordingly. For the smaller amount of data, sips are generating without any issues.

But for a huge number of data (> 2000000 records) am getting heap space issue.

Then I modified the code to create SIPs for each 100000 records. Even for this am getting an issue with memory.
Available RAM on the server is 4GB. On analysis, I found that sipAssembler is not cleared properly on the source code. I couldn't find any option clear the sipAssembler or FileBuffer explicitly.
Can anybody provide some comments or suggestions on this?
Regards,
Amuthan

**Comment by sgijsenot** [comment]
Hi @AmuthanGit,

Could you be a bit more specific with regards to where you think the buffers are not properly cleared? I reviewed the buffering in a few locations and those seem to be properly cleared after its task ends.

Thanks

**Comment by IgorNikiforov** [comment]
Hello @AmuthanGit,

Do you think it is possible to share with us the sample application in order to reproduce the case? 
Or even better to create a pull request with unit test to reproduce, so we are on the same page?

Thank you in advance.

**Comment by kovaloid** [comment]
Hi @AmuthanGit!

Could you please provide more information?

> For the smaller amount of data, sips are generating without any issues.

What is the exact amount of data the memory problem starts with?

> But for a huge number of data (> 2000000 records) am getting heap space issue.

How much space does the structured data and all related contents take on the disk before zipping to SIP?
And what kind of issue appears? Could you send the error message or logs?

Regards,
Artem

**Comment by torsv454** [comment]
Could it be so simple that you are just using a MemoryBuffer for the PDI instead of a FileBuffer. Which would happen if you don't supply a DataBuffer yourself and use the proper constructor, it is documented in the javadoc as follows: 

> For small PDIs, you can use a MemoryBuffer to hold this data, but for larger PDIs you should use a FileBuffer to prevent running out of memory.

For example you could use this constructor: 

```
  public SipAssembler(PackagingInformationFactory packagingInformationFactory,
      Assembler<HashedContents<D>> pdiAssembler, HashAssembler pdiHashAssembler,
Supplier<? extends DataBuffer> pdiBufferSupplier, ContentAssembler<D> contentAssembler) {
```

**Comment by AmuthanGit** [comment]
Hello All,

Thanks for the response.

I am out of office today. Tomorrow I will check the workaround given and
provide you the update.

regards,
Amuthan

**Comment by AmuthanGit** [comment]
Hello Tord,

Kindly find the below code which gives memory issue.

*SipAssembler<pojoClass> sipAssembler = SipAssembler.forPdi(eas_sip,
eas_pdi);*
* File sipFile = new File(sipDirectory + year + "-" + month + "_" +
UUID.randomUUID() + ".zip");*
* log.info <http://log.info>("SIP file: " + sipFile.getName());*
* FileBuffer fb = new FileBuffer(sipFile);*
* sipAssembler.start(fb);*
* while (rs1.next()) {*
* /* Add the required values to sipAssembler*
*/**
* sipAssembler.add(objectOf**pojoClass**);*
* }*
* sipAssembler.end();*

I couldn't clear the memory for the FileBuffer. Ending sipAssembler would
close all the used buffers internally?

Workaround: I was able to overcome the memory issue by explicitly calling
garbage collector.

Please correct me if I am missing anything.

Regards,
Amuthan
