### ISSUE TITLE
CDATA element creation through xmlbuilder

### ISSUE THREAD

**Issue by AmuthanGit** [Enterprise-Content-Management/infoarchive-sip-sdk#49]
We are having a text filed that has many special characters. So we would like to place that string inside the CDATA XML element so that it won't get validated against the schema. But I couldn't find an option to build the CDATA element through XmlBuilder.
Please provide an example to create a CDATA element through XmlBuilder.

regards,
Araamuthan
+91 8123810722
amuthansaranga@gmail.com

**Comment by IgorNikiforov** [comment]
Hello @AmuthanGit,
It looks like we are not providing direct API for XmlBuilder for adding CDATA. It is not implemented yet. 
However, I added a simple test to show how you can workaround your need.

**Comment by IgorNikiforov** [comment]
Hello @AmuthanGit,

We added missing API for CDATA in 11.2.13. 
Please take a look if it matches your needs. 
Please, fell free to create Pull Request for the missing functionality, if required. 
We will be glad to review and merge.  

Thank you.
