### ISSUE TITLE
Heap space issue with BatchAssembler

### ISSUE THREAD

**Issue by AmuthanGit** [Enterprise-Content-Management/infoarchive-sip-sdk#51]
Hello All,

I am reading a CSV file which has one million records and each records has 500 columns. I am able to read the records and create a POJA list post which i am trying to create SIP packages with 
XMLPdiAssembler and BatchAssembler where i have mentioned the limit is 1 million and get the below error while creating a SIP file.
Exception in thread "main" java.lang.OutOfMemoryError
	at java.io.ByteArrayOutputStream.hugeCapacity(ByteArrayOutputStream.java:123)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:117)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at java.io.PrintWriter.flush(PrintWriter.java:320)
	at com.opentext.ia.sdk.support.xml.PrintingXmlBuilder.build(PrintingXmlBuilder.java:149)
	at com.opentext.ia.sdk.support.xml.PrintingXmlBuilder.build(PrintingXmlBuilder.java:15)
	at com.opentext.ia.sdk.sip.XmlPdiAssembler.add(XmlPdiAssembler.java:122)
	at com.opentext.ia.sdk.sip.PdiAssembler.add(PdiAssembler.java:27)
	at com.opentext.ia.sdk.sip.PdiAssembler.add(PdiAssembler.java:15)
	at com.opentext.ia.sdk.sip.PrintWriterAssembler.add(PrintWriterAssembler.java:77)
	at com.opentext.ia.sdk.sip.SipAssembler.add(SipAssembler.java:317)
	at com.opentext.ia.sdk.sip.BatchSipAssembler.add(BatchSipAssembler.java:85)

When I reduce the  batch limit to 50000 I am able to create SIP packages but 50000 is too low count . As I have large files to process I need to use the limit as 1 million or half a million at least.
Below are the version of library and language I am using.
Java: 1.8 64 bit
IA SIP SDK: 11.1.0
Thanks in advance.

regards,
Araamuthan

**Comment by kovaloid** [comment]
Hi @AmuthanGit,

It seems that the PrintWriter buffer storing the contents of the PDI xml file in memory is not properly flushed, which subsequently leads to memory overflow.
I will take a look at this issue and try to provide the fix.

Regards,
Artem Kovalev

**Comment by kovaloid** [comment]
@AmuthanGit, could you please provide information about the CPU and the RAM size of the machine on which you run the SIP-SDK?
Do you use any Java -Xmx command-line parameters to limit memory usage?
When you run the SIP-SDK, how much memory is used?

**Comment by AmuthanGit** [comment]
The server were the the code is running is having 150GB RAM and i allocated
30 GB of RAM while running the code.
Yes,  I am using XMX to allocate 30GB RAM.
When i run the code it's consuming
whole 30GB to process even 500MB file.

**Comment by kovaloid** [comment]
@AmuthanGit 30GB RAM should be enough for this.
Could you please provide how you create SipAssembler? Do you define DataBuffer instance? If you use MemoryBuffer, could yo please try with FileBuffer?

**Comment by kovaloid** [comment]
@AmuthanGit you mentioned that have created a list of POJOs. Does this list contain 1 million objects? How much memory do they take?

**Comment by AmuthanGit** [comment]
Hi,

The code able to read the file and create a list and it consumes less
memory for that after that it's calling XmlPdiAssmbler and do add method to
add the elements.
Then i am calling batchSipAssembler and using FileSupplier.
Actually on the batchsipassembler part it's failing.

regards
Araamuthan

**Comment by AmuthanGit** [comment]
Hi,

If i use filbuffer instead of filesupplier woul it resolve the problem?

**Comment by kovaloid** [comment]
@AmuthanGit I suspect you are about fileSupplier which is the argument of the following constructor:
`public BatchSipAssembler(SipAssembler<D> assembler, SipSegmentationStrategy<D> segmentationStrategy, Supplier<File> fileSupplier)`

But I'm talking about SipAssembler which has DataBufferSupplier:
`new SipAssembler<>(factory, pdiAssembler, pdiHashAssembler, new DataBufferSupplier<>(MemoryBuffer.class), contentAssembler)`

As you can see in the code it uses MemoryBuffer by default, but it's possible to change it to FileBuffer. MemoryBuffer keeps all the PDI data in memory, but FileBuffer keeps it in the file.

**Comment by AmuthanGit** [comment]
Got it.
Currently am using sipassembler as below.
SipAssembler<> sipassembler = SipAssembler.forPdi(prototyle, pdiAssbler)

I hope the above suggestion you have would help me. Please correct me of I
Am wrong

**Comment by kovaloid** [comment]
@AmuthanGit good! And now instead of:
`SipAssembler<> sipassembler = SipAssembler.forPdi(prototyle, pdiAssbler)`

Try this:
`SipAssembler<> sipassembler = new SipAssembler<>(new DefaultPackagingInformationFactory(prototype), pdiAssembler, new NoHashAssembler(), new DataBufferSupplier<>(FileBuffer.class), ContentAssembler.ignoreContent())`

**Comment by AmuthanGit** [comment]
Thanks a lot. Now i can create sip for my csv file which has 1 million rows
and each row contains 500 columns.

I have one more question.
Current code is taking 25 min to process the above mentioned file.
Where the reading the file and creating beans takes only 8 min but the
BatchAssembler takes remaining 17 min.

Below is BatchAssembler method
BatchSipAssembler batchAssembler = new BatchSipAssembler<>(SipAssembler,
SipSegmentationStrategy.
bymaxaius(size),Filesupplier.fromDirector(oitputDir, fileName));

for(CSVData record : csbrecords)
{ batchAssembler.add(record);
}
batchAssembler.end();


Is there a way to enhance this?
or if i dont use batchSipAssemler will it increase the performance?

regards,
Araamuthan

**Comment by kovaloid** [comment]
@AmuthanGit great news! Actually 17 min for creating such big PDI and then zipping it in SIP file is reasonably good time. It is nothing to do in this case.

**Comment by AmuthanGit** [comment]
That makes sense. Thanks for the help.

regards,
Araamuthan
